/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Wavelength design system tokens
        'tertiary-fixed-dim': '#cebdff',
        'on-surface': '#e4e1e7',
        'outline': '#958ea0',
        'on-primary': '#3c0091',
        'secondary-fixed': '#b2f746',
        'primary': '#d0bcff',
        'primary-fixed': '#e9ddff',
        'on-primary-fixed-variant': '#5516be',
        'surface-bright': '#39393d',
        'surface-dim': '#131317',
        'on-background': '#e4e1e7',
        'on-primary-container': '#340080',
        'secondary-container': '#83c300',
        'on-secondary-fixed-variant': '#334f00',
        'secondary-fixed-dim': '#98da27',
        'on-tertiary-container': '#31057e',
        'surface': '#131317',
        'inverse-primary': '#6d3bd7',
        'on-primary-fixed': '#23005c',
        'on-surface-variant': '#cbc3d7',
        'surface-container-high': '#2a292e',
        'on-secondary-container': '#304b00',
        'on-tertiary-fixed': '#21005e',
        'tertiary-container': '#9b7fed',
        'on-tertiary-fixed-variant': '#4f319c',
        'outline-variant': '#494454',
        'background': '#131317',
        'on-error-container': '#ffdad6',
        'surface-tint': '#d0bcff',
        'on-secondary-fixed': '#121f00',
        'on-tertiary': '#381385',
        'on-secondary': '#213600',
        'primary-container': '#a078ff',
        'error-container': '#93000a',
        'inverse-surface': '#e4e1e7',
        'inverse-on-surface': '#303034',
        'surface-container-lowest': '#0e0e12',
        'surface-container-low': '#1b1b1f',
        'surface-container-highest': '#353439',
        'surface-variant': '#353439',
        'tertiary-fixed': '#e8ddff',
        'tertiary': '#cebdff',
        'secondary': '#9ddf2e',
        'primary-fixed-dim': '#d0bcff',
        'error': '#ffb4ab',
        'surface-container': '#1f1f23',
        'on-error': '#690005',
        // Legacy tokens for backward compat
        theme: {
          base: '#0e0e12',
          surface: '#1b1b1f',
          border: '#494454',
          text: '#e4e1e7',
          textMuted: '#958ea0',
          accent: '#d0bcff',
          accentHover: '#a078ff',
          accentMuted: '#2a1f4e',
          danger: '#ffb4ab',
          dangerMuted: '#2c1010',
          success: '#9ddf2e',
          successMuted: '#1a2e0a',
        },
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.25rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'gutter-sm': '0.75rem',
        margin: '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'stat-xl': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'label-sm': ['Inter'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Inter'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'stat-xl': ['32px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 8px rgba(208,188,255,0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(208,188,255,0.6)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.2s ease-out',
        pulseGlow: 'pulseGlow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
